class PdfDocument:
    def __init__(self) -> None: ...
    def add_page(self, width: float = 612.0, height: float = 792.0) -> Page: ...
    def to_bytes(self) -> bytes: ...
    def save(self, path: str) -> None: ...
    def register_font(self, font_db: FontDatabase, font_id: FontId) -> str: ...

class Page:
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def set_font(self, name: str, size: float) -> None: ...
    def draw_text(self, x: float, y: float, text: str) -> None: ...

class FontDatabase:
    def __init__(self) -> None: ...
    def load_system_fonts(self) -> None: ...
    def load_font_file(self, path: str) -> FontId: ...
    def load_font_data(self, data: bytes) -> FontId: ...
    def query(
        self, family: str, weight: int = 400, italic: bool = False
    ) -> FontId | None: ...

class FontId:
    def __init__(self) -> None: ...
